### ISSUE TITLE
stack-packet docker image not published to docker hub under crossplane

### ISSUE THREAD

**Issue by botwhytho** [hasheddan/stack-packet-demo#13]
Deploying the below yaml doesn't currently work as it tries to create a pod that tries to pull the non-existent image `docker.io/crossplane/stack-packet:latest`

```yaml
apiVersion: stacks.crossplane.io/v1alpha1
kind: ClusterStackInstall
metadata:
  name: "crossplane-stack-packet"
spec:
  package: "crossplane/stack-packet"
```

Can someone build and push that image?
